# Generated by Django 4.2.4 on 2023-10-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_options_alter_post_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
